export const allRecipeIngredients = [
  "dirsek makarna",
  "karabiber",
  "kaşar peyniri",
  "muskat",
  "süt",
  "tereyağı",
  "tuz",
  "un",
  "domates",
  "kuru patlıcan",
  "nane",
  "nar ekşisi",
  "pirinç",
  "pul biber",
  "soğan",
  "su",
  "zeytinyağı",
  "salça",
  "tarhana",
  "havuç",
  "kimyon",
  "kırmızı mercimek",
  "yoğurt",
  "yumurta sarısı",
  "domates rendesi / konserve",
  "su / et suyu",
  "şeker",
  "brokoli",
  "krema",
  "patates",
  "sarımsak",
  "balkabağı",
  "kabak",
  "kereviz",
  "limon suyu",
  "kekik",
  "lahana",
  "arpa şehriye",
  "aşurelik buğday",
  "dereotu/nane",
  "asma yaprağı",
  "dolmalık fıstık",
  "kuş üzümü",
  "limon",
  "yenibahar",
  "bezelye",
  "pırasa",
  "kabartma tozu",
  "sıvı yağ",
  "tarçın",
  "yumurta",
  "beyaz peynir",
  "yufka",
  "çörek otu",
  "maydanoz",
  "spagetti",
  "mantar",
  "parmesan",
  "penne",
  "fesleğen",
  "dana kıyma",
  "karides",
  "linguine",
  "pastırma",
  "pecorino",
  "tavuk göğsü",
  "nohut",
  "kapya biber",
  "bamya",
  "haşlanmış nohut",
  "kuru fasulye",
  "marul",
  "mor lahana",
  "mısır",
  "roka",
  "salatalık",
  "siyah zeytin",
  "burgu makarna",
  "dereotu",
  "kornişon turşu",
  "kırmızı biber",
  "mayonez",
  "kinoa",
  "taze soğan",
  "ıspanak",
  "ince bulgur",
  "kırmızı soğan",
  "karnabahar",
  "ceviz",
  "pancar",
  "levrek",
  "bulgur",
  "somon fileto",
  "patlıcan",
  "biber",
  "dana kuşbaşı",
  "enginar",
  "hamsi",
  "mısır unu",
  "avokado",
  "nori",
  "pirinç sirkesi",
  "somon",
  "sushi pirinci",
  "tortilla",
  "sivri biber",
  "midye",
  "safran",
  "tavuk",
  "acı biber",
  "kırmızı fasulye",
  "soğan suyu",
  "toz kırmızı biber",
  "kereviz sapı",
  "tavuk but",
  "biberiye",
  "yeşil biber",
  "beyaz lahana",
  "tavuk baget",
  "acı sos",
  "tavuk kanat",
  "kuzu kuşbaşı",
  "dana sotelik",
  "haşlanmış kuru fasulye",
  "pirinç eriştesi",
  "soya sosu",
  "yer fıstığı",
  "kıyma",
  "dana but",
  "garam masala",
  "zencefil",
  "bal",
  "muz",
  "çilek",
  "bisküvi",
  "nişasta",
  "kakao",
  "irmik",
  "maya",
  "pekmez",
  "susam",
  "çikolata",
  "karabuğday unu",
  "kahve",
  "kedi dili",
  "labne",
  "glutensiz un karışımı",
  "kolot peyniri",
  "ekmek",
  "kalamar",
  "ton balığı",
  "barbunya",
  "tofu",
  "taze bakla",
  "pirinç unu",
  "taze fasulye",
  "pazı",
  "domates sosu",
  "mozzarella",
  "sucuk",
  "zeytin",
  "semizotu",
  "brüksel lahanası",
  "vanilya",
  "hardal",
  "kruton",
  "limon kabuğu",
  "dolmalık biber",
  "haşlanmış yeşil mercimek",
  "kişniş",
  "tahin",
  "yeşil mercimek",
  "nohut unu",
  "haşlanmış kuru börülce",
  "haşlanmış maş fasulyesi",
  "çipura",
  "cheddar peyniri",
  "hamburger ekmeği",
  "ketçap",
  "turşu",
  "balık",
  "fusilli",
  "kapari",
  "tavuk kuşbaşı",
  "köri",
  "pesto sos",
  "defne yaprağı",
  "lavaş",
];
